experiments:
#Ground Truth Experiments with Chimera 4x4x4

# - id: 1
#   logical_graph: graphs/bipartito4x4.txt
#   logical_graph_json: graphs/bipartito4x4.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/1/reduced/reduced_physical_1.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
#
# - id: 2
#   logical_graph: graphs/cycle8.txt
#   logical_graph_json: graphs/cycle8.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/2/reduced/reduced_physical_2.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 3
#   logical_graph: graphs/grid2x3.txt
#   logical_graph_json: graphs/grid2x3.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/3/reduced/reduced_physical_3.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 4
#   logical_graph: graphs/path8.txt
#   logical_graph_json: graphs/path8.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/4/reduced/reduced_physical_4.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 5
#   logical_graph: graphs/star4.txt
#   logical_graph_json: graphs/star4.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/5/reduced/reduced_physical_5.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 6
#   logical_graph: graphs/tree10.txt
#   logical_graph_json: graphs/tree10.json
#   physical_graph: graphs/chimera5x5x4.txt
#   physical_graph_json: graphs/chimera5x5x4.json
#   reduce_physical_graph: outputs/6/reduced/reduced_physical_6.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# - id: 7
#   logical_graph: graphs/clique4.txt
#   logical_graph_json: graphs/clique4.json
#   physical_graph: graphs/pegasus2.txt
#   physical_graph_json: graphs/pegasus2.json
#   reduce_physical_graph: outputs/7/reduced/reduced_physical_7.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 8
#   logical_graph: graphs/wheel4.txt
#   logical_graph_json: graphs/wheel4.json
#   physical_graph: graphs/pegasus2.txt
#   physical_graph_json: graphs/pegasus2.json
#   reduce_physical_graph: outputs/8/reduced/reduced_physical_8.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 9
#   logical_graph: graphs/bipartito6x6.txt
#   logical_graph_json: graphs/bipartito6x6.json
#   physical_graph: graphs/pegasus2.txt
#   physical_graph_json: graphs/pegasus2.json
#   reduce_physical_graph: outputs/9/reduced/reduced_physical_9.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 10
#   logical_graph: graphs/cycle8.txt
#   logical_graph_json: graphs/cycle8.json
#   physical_graph: graphs/pegasus2.txt
#   physical_graph_json: graphs/pegasus2.json
#   reduce_physical_graph: outputs/10/reduced/reduced_physical_10.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 11
#   logical_graph: graphs/fan6.txt
#   logical_graph_json: graphs/fan6.json
#   physical_graph: graphs/pegasus2.txt
#   physical_graph_json: graphs/pegasus2.json
#   reduce_physical_graph: outputs/11/reduced/reduced_physical_11.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 12
#   logical_graph: graphs/clique4.txt
#   logical_graph_json: graphs/clique4.json
#   physical_graph: graphs/zephyr2.txt
#   physical_graph_json: graphs/zephyr2.json
#   reduce_physical_graph: outputs/12/reduced/reduced_physical_12.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 13
#   logical_graph: graphs/bipartito8x8.txt
#   logical_graph_json: graphs/bipartito8x8.json
#   physical_graph: graphs/zephyr2.txt
#   physical_graph_json: graphs/zephyr2.json
#   reduce_physical_graph: outputs/13/reduced/reduced_physical_13.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# 
# - id: 14
#   logical_graph: graphs/grid3x3.txt
#   logical_graph_json: graphs/grid3x3.json
#   physical_graph: graphs/zephyr2.txt
#   physical_graph_json: graphs/zephyr2.json
#   reduce_physical_graph: outputs/14/reduced/reduced_physical_14.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 30
#   check_treewidth: false
#   generate_full_and_reduced: true
# - id: 15
#   logical_graph: graphs/fan6.txt
#   logical_graph_json: graphs/fan6.json
#   physical_graph: graphs/zephyr2.txt
#   physical_graph_json: graphs/zephyr2.json
#   reduce_physical_graph: outputs/15/reduced/reduced_physical_15.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 3360
#   check_treewidth: false
#   generate_full_and_reduced: true
#
# - id: 16
#   logical_graph: graphs/wheel4.txt
#   logical_graph_json: graphs/wheel4.json
#   physical_graph: graphs/zephyr2.txt
#   physical_graph_json: graphs/zephyr2.json
#   reduce_physical_graph: outputs/16/reduced/reduced_physical_16.json
#   max_chain_length: 1
#   allow_shared_physical_qubits: false
#   timeout_seconds: 3360
#   check_treewidth: false
#   generate_full_and_reduced: true

#  - id: 17
#    logical_graph: graphs/grid3x3x3.txt
#    logical_graph_json: graphs/grid3x3x3.json
#    physical_graph: graphs/zephyr2.txt
#    physical_graph_json: graphs/zephyr2.json
#    reduce_physical_graph: outputs/17/reduced/reduced_physical_17.json
#    max_chain_length: 1
#    allow_shared_physical_qubits: false
#    timeout_seconds: 3360
#    check_treewidth: false
#    generate_full_and_reduced: true
#   - id: 18
#     logical_graph: graphs/grid2x2x2.txt
#     logical_graph_json: graphs/grid2x2x2.json
#     physical_graph: graphs/pegasus3.txt
#     physical_graph_json: graphs/pegasus3.json
#     reduce_physical_graph: outputs/18/reduced/reduced_physical_18.json
#     max_chain_length: 1
#     allow_shared_physical_qubits: false
#     timeout_seconds: 3360
#     check_treewidth: false
#     generate_full_and_reduced: true 



output_dir: outputs
solver: glucose
